Refactored scripts

diff --git a/.local/bin/cursor b/.local/bin/cursor
--- a/.local/bin/cursor
+++ b/.local/bin/cursor
@@ -4,150 +4,184 @@
 # File: ~/.local/bin/cursor
 #
 
-###############################################################################
-# Functions
+#··············································································
+# Variables {{{
 
-# https://stackoverflow.com/a/8574392
-set +e #otherwise the script will exit on error
-containsElement () {
-  local e match="$1"
-  shift
-  for e; do [[ "$e" == "$match" ]] && return 0; done
-  return 1
+programName="$(basename $0)"
+
+xdgConfig="${XDG_CONFIG_HOME:-$HOME/.config}"
+xdgData="${XDG_DATA_HOME:-$HOME/.local/share}"
+
+# Cursor themes located at local icons won't apply to system wide configuration
+# For example, for the window manager in the case of Qtile
+localIcons="${xdgData}/icons"
+globalIcons="/usr/share/icons"
+
+defaultTheme="$(sed -n -E '/^Inherits=(.*)$/s//\1/p' \
+                 ${globalIcons}/default/index.theme)"
+
+themeFiles=( "${xdgConfig}/X11/Xresources" "$HOME/.Xresources" )
+
+themes=()
+
+# }}}
+
+
+#··············································································
+# Functions {{{
+
+function info_program() {
+cat << EOF
+Usage: $programName [OPTION] [THEME]
+
+Set cursor theme.
+
+Options:
+  -h, --help           display this help and exit
+  -l, --list-themes    list installed cursor themes
+  -s, --set-theme      set cursor to specified theme
+
+If no option is passed the current cursor theme will be shown
+EOF
 }
 
-###############################################################################
-# Program
+function show_current() {
+    local currentTheme="$(sed -n -E \
+        '/Xcursor\.theme:\s*(.*)$/s//\1/p' <(xrdb -query))"
 
-# Show help
-if [ $# == 1 ] && ([ $1 == "--help" ] || [ $1 == "-h" ]); then
-  echo
-  echo "Usage:"
-  echo " cursor [options]"
-  echo
-  echo "Sets cursor theme."
-  echo
-  echo "Options:"
-  echo " -s, --set-cursor <theme>  sets cursor theme to <theme>"
-  echo " --show-cursors            show installed cursor themes"
-  echo " --show-current            show currently used cursor theme"
-  echo " -h, --help                display this help"
-  echo
-  echo "If no option is given the program will use '--show-current' option"
-  exit 0
+    echo "Current theme: ${currentTheme:-$defaultTheme}"
+}
+
+function get_themes() {
+    while IFS= read -r line
+    do
+        themes+=("$line")
+    done < <(find $globalIcons $localIcons -type d -name "cursors" | 
+             awk -F '/' '{print $(NF-1)}')
+    unset IFS
+}
+
+function check_arg() {
+    get_themes
+    for theme in "${themes[@]}"
+    do
+        [ "$theme" = "$1" ] && return 0
+    done
+    return 1
+}
+
+function set_theme() {
+    local newTheme="$1"
+    local xresParam="Xcursor.theme"
+    local themeIndex=0
+    local themeFile="${themeFiles[$themeIndex]}"
+
+    if ! [ -f "$themeFile" ]
+    then
+        echo -n -e \
+            "No Xresources file was found." "\n" \
+            "\bSelect where to create it:" "\n" \
+            "\b  1 $HOME/.config/X11/Xresources" "\n" \
+            "\b  2 $HOME/.Xresources" "\n" \
+            "\bEnter a selection (default=1): "
+        read themeIndex
+
+        themeIndex=${themeIndex:-1}
+        [ $themeIndex -lt 1 ] || [ $themeIndex -gt 2 ] && {
+            echo "Invalid selection: Aborting."; 
+            exit 1;
+        }
+        ((themeIndex--))
+
+        # Update the file theme selected
+        themeFile="${themeFiles[$themeIndex]}"
+    fi
+    mkdir -p "$(dirname $themeFile)"
+    touch "$themeFile"
+
+    # Write the theme in the Xresources file
+    if [ "$(grep $xresParam: $themeFile)" = "" ]
+    then
+        # If it didn't exist, just add it to the file
+        echo "${xresParam}: $newTheme" >> "$themeFile"
+    else
+        # Otherwise modify it with sed
+        sed -i -E "s/${xresParam}:[[:space:]]+.*$/${xresParam}: ${newTheme}/" \
+                  "$themeFile"
+    fi
+    
+    # Reload Xresources with xrdb
+    xrdb -load "$themeFile"
+
+    # Set the global theme for other applications (e.g. display manager)
+    local tmpFile="$(mktemp)"
+    cat "${globalIcons}/default/index.theme" > "$tmpFile"
+    sed -i -E "s/^Inherits=.*$/Inherits=${newTheme}/" "$tmpFile"
+    cat "$tmpFile" > "${globalIcons}/default/index.theme"
+    rm "$tmpFile"
+
+    echo "Theme set to '$newTheme'"
+
+    return 0
+}
+
+function list_themes() {
+    get_themes
+    for theme in "${themes[@]}"
+    do
+        echo -n "$theme"
+        echo "$( [ $theme = $defaultTheme ] && echo ' (default)' )"
+    done
+}
+
+# }}}
+
+
+#··············································································
+# Main {{{
+
+if [ $# -eq 0 ]
+then
+    show_current
+    exit 0
 fi
 
-
-# Nº of arguments check
-if [ $# -gt 2 ]; then
-  echo "cursor: error no more than 2 arguments were expected"
-  echo "Try 'cursor --help' for more information."
-  exit 1
-elif [ $# -eq 2 ] && [ "$1" != "-s" ] && [ "$1" != "--set-cursor" ]; then
-  echo "cursor: error only option '--set-cursor' expects 2 arguments"
-  echo "Try 'cursor --help' for more information."
-  exit 1
-elif ([ "$1" == "s" ] || [ "$1" == "--set-cursor" ]) && [ $# != 2 ]; then
-  echo "cursor: error option '$1' expected another argument"
-  echo "Try 'cursor --help' for more information."
-  exit 1
+if [ $# -gt 2 ]
+then
+    echo "$programName: too many arguments"
+    echo "Try '$programName --help' for more information."
+    exit 1
 fi
 
-local_theme="$XDG_DATA_HOME/icons/default/index.theme"
-global_theme="/usr/share/icons/default/index.theme"
+case "$1" in
+    "-h" | "--help")
+        info_program
+        exit 0
+        ;;
+    "-s" | "--set-theme")
+        if [ $# -ne 2 ]
+        then
+            echo "$programName: no theme was passed"
+            echo "Use '$programName --list-themes' to list available themes."
+            exit 1
+        elif ! check_arg $2
+        then
+            echo "$programName: unrecognized theme '$2'"
+            echo "Use '$programName --list-themes' to list available themes."
+            exit 1
+        fi
+        set_theme $2
+        exit 0
+        ;;
+    "-l" | "--list-themes")
+        list_themes
+        exit 0
+        ;;
+    *)
+        echo "$programName: unrecognized option '$1'"
+        echo "Try '$programName --help' for more information."
+        exit 1
+        ;;
+esac
 
-# Default behaviour
-if [ $# -eq 0 ] || ([ $# -eq 1 ] && [ "$1" == "--show-current" ]); then
-  declare aux
-  if test -e $local_theme ; then
-    aux="$(tail -1 $local_theme)"
-  elif test -e $global_theme ; then
-    aux="$(tail -1 $global_theme)"
-  fi
-
-  aux_array=(${aux//=/ })
-  current_theme=${aux_array[1]}
-
-  echo $current_theme
-
-  exit 0
-fi
-
-
-# List of installed cursor themes (*)
-
-declare -a themes=()
-
-while IFS= read -r line; do
-  aux_array=(${line//// })
-
-  declare -i i=0
-
-  # Could be improved using Regex =~
-  while ([ "${aux_array[$i]}" != ".icons" ] && [ "${aux_array[$i]}" != "icons" ]) ; do
-    i=$i+1
-  done
-
-  themes+=("${aux_array[$i+1]}")
-
-done <<< "$(find /usr/share/icons $XDG_DATA_HOME/icons/ -type d -name "cursors")"
-unset IFS
-
-
-if [ "$1" == "-s" ] || [ "$1" == "--set-cursor" ]; then
-  containsElement "$2" "${themes[@]}"
-
-  if [ $? == 1 ]; then
-    echo "cursor: '$2' is not a valid cursor theme"
-    echo "To see all installed cursor themes try 'cursor --show-cursors'"
-    echo "Try 'cursor --help' for more information."
-    exit 2
-  fi
-
-  tmp_file="/tmp/tmp_file"
-
-  echo -e "[Icon Theme]\nInherits=$2" > $tmp_file
-  cat $tmp_file > $local_theme
-  sudo bash -c "cat \"$tmp_file\" > $global_theme"
-
-
-  head -7 $GTK2_RC_FILES > $tmp_file
-  echo "gtk-cursor-theme-name=\"$2\"" >> $tmp_file
-  tail -10 $GTK2_RC_FILES >> $tmp_file
-  cat $tmp_file > $GTK2_RC_FILES
-
-  head -4 $XDG_CONFIG_HOME/gtk-3.0/settings.ini > $tmp_file
-  echo "gtk-cursor-theme-name=\"$2\"" >> $tmp_file
-  tail -10 $XDG_CONFIG_HOME/gtk-3.0/settings.ini >> $tmp_file
-  cat $tmp_file > $XDG_CONFIG_HOME/gtk-3.0/settings.ini
-
-  rm $tmp_file
-  
-  echo "Cursor theme set to $2"
-
-  exit 0
-fi
-
-
-if [ "$1" == "--show-cursors" ]; then
-  for theme in "${themes[@]}"; do
-    echo $theme
-  done
-
-  exit 0
-fi
-
-
-# If it has reached this point, the first parameter wasn't any of the
-# valid options
-echo "cursor: option '$1' unrecognized"
-echo "Try 'cursor --help' for more information."
-exit 1
-
-
-
-# * The solution is a mix of reading line by line and processing each line by
-# splitting it into multiple strings, storing them into an array and using
-# the value that is useful
-# https://stackoverflow.com/a/10929511
-# https://stackoverflow.com/a/5257398
+# }}}
diff --git a/.local/bin/percentage b/.local/bin/percentage
--- a/.local/bin/percentage
+++ b/.local/bin/percentage
@@ -4,131 +4,188 @@
 # File: ~/.local/bin/percentage
 #
 
-###############################################################################
-# Functions
+#··············································································
+# Variables {{{
 
-function divide() {
-  if [ $# -eq 2 ]; then
-    # Format: float with 2 decimals filled with 0 in case they are "empty"
-    solution=$(python -c "a='{:05.2f}'.format($1/$2); print(f'{a}')")
+programName="$(basename $0)"
 
-    echo "$solution"
-  elif [ $# -eq 3 ] && [ $3 == "-i" ]; then
-    # Format: integer
-    solution=$(python -c "print(f'{int($1//$2)}')")
+number="$1"
+values=($@)
 
-    echo "$solution"
-  fi
+# }}}
+
+
+#··············································································
+# Functions {{{
+
+function info_program() {
+cat << EOF
+Usage: $programName NUMBER [OPTION] [VALUES]
+
+Prints one of the given values depending of the number passed.
+The values are assigned proportionally, e.g. if arguments are:
+'30 one two three' then 'one' will be returned because it's in
+the first range of [0, 33] [33, 66] [66, 100]
+
+NUMBER is a positive integer in range [0, 100]
+
+Options:
+  -h, --help           display this help and exit
+  -e, --examples       display some examples on how to use the program
+  -r, --repeat         if present two other parameters are needed:
+                         string to repeat
+                         max
+Values:
+  value1 value2 ...  values are given as parameters
+  file               values are written inside a file
+
+File format: Values must be in the same line separated by spaces ' '
+EOF
 }
 
-###############################################################################
-# Program
+function show_examples() {
+cat << EOF
+Examples:
 
-# Show help
-if [ $# -eq 1 ] && ([ "$1" == "-h" ] || [ "$1" == "--help" ]); then
-  echo
-  echo "Usage:"
-  echo "percentage <number> [option] <values>"
-  echo
-  echo "Prints one of the given values depending of the number passed."
-  echo "The values are assigned proportionally, e.g. if arguments are:"
-  echo "'30 one two three' then 'one' will be returned because it's in"
-  echo "the first range of [0, 33] [33, 66] [66, 100]"
-  echo
-  echo " <number> is a positive integer in range [0, 100]"
-  echo
-  echo "Option:"
-  echo " --repeat if present two other parameters are needed:"
-  echo "           value that will be repeated to represent the % over the max"
-  echo "           an integer that represents the max"
-  echo
-  echo "Valid values:"
-  echo " value1 value2 ...  values are given as parameters"
-  echo " file               values are written inside a file"
-  echo
-  echo "File format: Values must be in the same line separated by spaces ' '"
-  exit 0
+$programName 15 Q1 Q2 Q3 Q4
+    -> Q1
+
+$programName 34% Q1 Q2 Q3 Q4
+    -> Q2
+
+$programName 70 Q1 Q2 Q3
+    -> Q3
+
+echo -n "Q1 Q2 Q3" > file.txt
+$programName 70 file.txt
+    -> Q3
+
+$programName 20 --repeat / 10
+    -> //
+
+$programName 20% --repeat A 5
+    -> A
+
+$programName 50% --repeat n/ 10
+-> n/n/n/n/n/n/
+
+EOF
+}
+
+function check_number() {
+    echo "$number" | grep -qP '^[0-9]+%?$' && number="${number//%/}" && return 0
+    return 1
+}
+
+function divide() {
+    local n1=$(printf "%.0f" "$1")
+    local n2=$(printf "%.0f" "$2")
+    local result=$(( $n1 / $n2 ))
+
+    if [ $# -eq 2 ]
+    then
+        local quotient=$(( 10**2 * $n1 / $n2 ))
+        local integerPart=$(( quotient / 100 ))
+        local decimalPart=$(( quotient % 100 ))
+        result=$(printf "%d.%02d\n" $integerPart $decimalPart)
+    fi
+
+    echo "$result"
+
+    return 0
+}
+
+function normal_mode() {
+    [ $number -ge 100 ] && echo -n "${values[-1]}" && return 0
+
+    local intervalSize=$(divide 100 ${#values[@]})
+    local interval=$(divide $number $intervalSize -i)
+    echo -n "${values[$interval]}"
+
+    return 0
+}
+
+function repeat_mode() {
+    local repString=$1
+    local max=$2
+
+    local times=$(python3 -c "print(f'{min(int($number / 100 * $max)+1, $max)}')")
+
+    for ((i = 0; i < $times; i++))
+    do
+        echo -n "$repString"
+    done
+
+    return 0
+}
+
+# }}}
+
+
+#··············································································
+# Main {{{
+
+
+case "$1" in
+    "-h" | "--help")
+        info_program
+        exit 0
+        ;;
+    "-e" | "--examples")
+        show_examples
+        exit 0
+        ;;
+esac
+
+
+if [ $# -lt 2 ]
+then
+    echo "$programName: too few arguments"
+    echo "Try '$programName --help' for more information."
+    exit 1
 fi
 
-# Incorrect amount of arguments
-if [ $# -lt 2 ]; then
-  echo "Error. At least 2 arguments were expected."
-  echo "Try 'percentage --help' for more information."
-  exit 1
+
+if ! check_number
+then
+    echo "$programName: expected a number but received '$number'"
+    echo "Try '$programName --help' for more information."
+    exit 1
+elif [ $number -gt 100 ]
+then
+    echo "$programName: the number must be an integer in [0, 100]"
+    echo "Try '$programName --help' for more information."
+    exit 1
 fi
 
-# Format the 1st argument to remove any % characters
-if [[ "$1" == *% ]]; then
-  number=${1::-1}
-else
-  number=$1
+# If number is 0 then print the empty string ""
+[ $number -eq 0 ] && echo -n "" && exit 0
+
+# Repeat must be the 2nd option passed for backward compatibility
+if [ $# -eq 4 ] && ([ "$2" = "-r" ] || [ "$2" = "--repeat" ])
+then
+    repeat_mode $3 $4
+    exit 0
 fi
 
-# Wrong number
-#if [ $number -lt 0 ] || [ $number -gt 100 ]; then
-# Allows number > 100 for supporting volume over 100%
-if [ $number -lt 0 ]; then
-  echo "Error. 1st argument must be a positive integer in range [0, 100]"
-  echo "Try 'percentage --help' for more information."
-  exit 1 
-fi
+case "$1" in
+    "-"*)
+        echo "$programName: unrecognized option '$1'"
+        echo "Try '$programName --help' for more information."
+        exit 1
+        ;;
+    *)
+        values=("${values[@]:1}")
+        if [ $# -eq 2 ] && read -r -a values < "$2" 2> /dev/null
+        then
+            echo "$programName: error while reading file '$2'"
+            echo "Try '$programName --help' for more information."
+            exit 1
+        fi
 
-# In both modes when the number is 0 nothing is printed
-if [ $number -eq 0 ]; then
-  echo -n ""
-  exit 0
-fi
+        normal_mode
+        exit 0
+        ;;
+esac
 
-
-# "Repeat" mode
-if [ $# -eq 4 ] && [ "$2" == "--repeat" ]; then
-  value=$3
-  max=$4
-
-  times=$(python -c "print(f'{min(int($number / 100 * $max)+1, $max)}')")
-
-  for ((i = 0; i < $times; i++))
-  do
-    echo -n "$value"
-  done
-
-  exit 0
-fi
-
-
-# "Normal" mode
-# Declarations
-declare -a values
-
-# Arguments passed in a file
-if [ $# -eq 2 ]; then
-  if !(test -e $2); then
-    echo "Error. File $2 doesn't exist."
-    echo "Try 'percentage --help' for more information."
-    exit 2
-  elif !(test -r $2); then
-    echo "Error. Read acces to $2 denied."
-    echo "Try 'percentage --help' for more information."
-    exit 2
-  fi
-
-  read -r -a values < $2
-else
-  declare -a arguments=("$@") # Doesn't include program's name
-  for ((i = 1; i < $#; i=i+1))
-  do
-    values+=("${arguments[i]}")
-  done
-fi
-
-
-# If value is 100, it's in the last interval
-if [ $number -ge 100 ]; then
-  echo -n "${values[-1]}"
-else
-  # Calculate interval to which the number belongs
-  interval_size=$(divide 100 ${#values[@]})
-  interval=$(divide $number $interval_size -i)
-
-  echo -n "${values[$interval]}"
-fi
+# }}}
diff --git a/.local/bin/set-monitor b/.local/bin/set-monitor
--- a/.local/bin/set-monitor
+++ b/.local/bin/set-monitor
@@ -4,118 +4,171 @@
 # File: ~/.local/bin/set-monitor
 #
 
-################################################################################
-# Variable declarations
+#··············································································
+# Variables {{{
 
-directionArray=("up" "right" "down" "left")
-posArray=("0x-1080" "1920x0" "0x1080" "-1920x0")
-upArray=("up" "u" "north" "n")
-downArray=("down" "d" "south" "s")
-rightArray=("right" "r" "east" "e")
-leftArray=("left" "l" "west" "w")
-
-programName=$0
 default=1
+upArray=("up" "u" "north" "n" "above")        # 0
+rightArray=("right" "r" "east" "e")           # 1
+downArray=("down" "d" "south" "s" "below")    # 2
+leftArray=("left" "l" "west" "w")             # 3
+arraysNames=("upArray" "rightArray" "downArray" "leftArray")
+directionArray=("--above" "--right-of" "--below" "--left-of")
 
-error_code=10
+monitors=()
+connectedMonitors=()
+mainMonitor=""
+numMonitors=$(xrandr | grep 'connected' | wc -l)
 
-################################################################################
-# Functions
+programName="$(basename $0)"
+
+errorCode=10
+
+# }}}
+
+
+#··············································································
+# Functions {{{
 
 function info_program() {
-    echo "Use: $programName <position>"
-    echo "<position> is an optional argument which indicates the position of" \
-         "the second screen relative to the main screen. If <position>" \
-         "argument is skipped then it will use the default" \
-         "(${posArray[$default]})" ; echo
-    echo "Valid values (both lower and upper case valid): "
-    echo "Up    : ${upArray[*]^}"
-    echo "Down  : ${downArray[*]^}"
-    echo "Right : ${rightArray[*]^}"
-    echo "Left  : ${leftArray[*]^}"
+defaultDirection="$(local a=${arraysNames[$default]}; echo ${!a[0]})"
+cat << EOF
+Usage: $programName [OPTION] [POSITION]
+
+Set secondary monitor position relative to the primary monitor.
+
+Options:
+  -h, --help    display this help and exit
+  -m, --mirror  mirror the output of primary monitor
+
+Positions (case insensitive):
+  ${upArray[*]^}
+  ${rightArray[*]^}
+  ${downArray[*]^}
+  ${leftArray[*]^}
+
+If no position is passed '${defaultDirection}' is used.
+If the option mirror is passed then no position must be passed.
+EOF
 }
 
-function set_monitor() {
-    hdmi=`xrandr | grep ' connected' | grep 'HDMI' | awk '{print $1}'`
+function get_monitors() {
+    # Create temporal file to store output of commands
+    tmpFile=$(mktemp)
+
+    xrandr | grep 'connected' | awk '{print $1}' > $tmpFile
+    while IFS= read -r line
+    do
+        monitors+=("$line")
+    done < $tmpFile
+
+    xrandr | grep -P ' connected' | awk '{print $1}' > $tmpFile
+    while IFS= read -r line
+    do
+        connectedMonitors+=("$line")
+    done < $tmpFile
+
+    # Delete the temporal file
+    rm $tmpFile
+
+    # Assign mainMonitor
+    # By default the monitor targeted as primary
+    mainMonitor="$(xrandr | grep 'primary' | awk '{print $1}')"
+    # Otherwise the one considered first by xrandr
+    [ "$mainMonitor" = "" ] && mainMonitor="${connectedMonitors[0]}"
+}
+
+function get_direction() {
+    local option="${1,,}"   # Convert to lowercase
+
+    for i in "${!arraysNames[@]}"
+    do
+        currentArray="${arraysNames[i]}[@]"
+        for element in "${!currentArray}"
+        do
+            [ "$option" = "${element,,}" ] && echo -n "$i" && return 0
+        done
+    done
     
-    # Set monitor
-    if [ "$hdmi" = "HDMI-1" ]; then
-        echo "Setting new screen ${directionArray[$1]} relative to main screen"
-        xrandr \
-        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
-        --output HDMI-1 --mode 1920x1080 --pos ${posArray[$1]} --rotate normal \
-        --output DP-1 --off \
-        --output DP-2 --off &
-    else
-        echo "Only the main screen was detected."
-        xrandr \
-        --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
-        --output HDMI-1 --off \
-        --output DP-1 --off \
-        --output DP-2 --off &
-    fi
+    echo -n "$errorCode"
+}
+
+function manage_monitors() {
+    get_monitors
     
-    # Reload qtile
-    qtile cmd-obj -o cmd -f restart
+    local params=""
+
+    for i in "${connectedMonitors[@]}"
+    do
+        [ "$i" = "$mainMonitor" ] && continue
+
+        if [ "$1" = "set" ]
+        then
+            params+=$(printf -- "--output %s --auto %s %s " \
+                                "$i" "${directionArray[$2]}" "$mainMonitor")
+        elif [ "$1" = "mirror" ]
+        then
+            params+=$(printf -- "--output %s --auto --same-as %s " \
+                                "$i" "$mainMonitor")
+        fi
+    done
     
+    xrandr $params && return 0
+
+    echo "An error occurred executing 'xrandr $params'"
+    exit 1
+}
+
+# }}}
+
+
+#··············································································
+# Main {{{
+
+# Default behaviour
+if [ $# -eq 0 ]
+then
+    manage_monitors "set" $default
     exit 0
-}
+fi
 
-################################################################################
-# Argument check
-
-if [ $# -gt 1 ]; then
-    echo "Error. Too many arguments. This program takes as much as 1 argument."
-    echo "For help use: $0 -h"
+# TODO: Support for adjusting multiple monitors
+# Impediments: Extremely likely that the user won't know the order in which 
+# the video ports are wired, so it may be unintuitive at first
+# if [ $# -gt $numMonitors ]
+if [ $# -ne 1 ]
+then
+    echo "$programName: too many arguments"
+    echo "Try '$programName --help' for more information."
     exit 1
 fi
 
-if [ $# -eq 1 ] && ([ "$1" == "-h" ] || [ "$1" == "--help" ]); then
-    info_program
-    exit 0
-fi
-
-if [ $# -eq 0 ]; then
-    set_monitor $default
-fi
-
-# Argument verification
 # If the program has reached this point, then there is exactly one argument
-option="${1,,}"
+case "$1" in
+    "-h" | "--help")
+        info_program
+        exit 0
+        ;;
+    "-m" | "--mirror")
+        manage_monitors "mirror"
+        exit 0
+        ;;
+    "-"*)
+        echo "$programName: unrecognized option '$1'"
+        echo "Try '$programName --help' for more information."
+        exit 1
+        ;;
+esac
 
-~/.local/bin/c_program/get_direction $option
-declare -i direction=$?
+direction=$(get_direction "$1")
 
-if [[ $direction -eq $error_code ]]; then
-    echo "Argument $1 is not a valid value."
-    echo "For help use: $0 -h"
-    exit 3
+if [ $direction -eq $errorCode ]
+then
+    echo "$programName: unrecognized direction '$1'"
+    echo "Try '$programName --help' for more information."
+    exit 1
 fi
 
-set_monitor $direction
+manage_monitors "set" $direction
 
-################################################################################
-
-# NOT WORKING AS DESIRED, IF POSSIBLE IT WOULD BE BETTER TO IMPLEMENT THE 
-# WHOLE PROGRAM IN BASH WITHOUT MAKING USE OF EXTERNAL PROGRAMS
-#if [[ "${upArray[@]}" =~ $option ]]; then
-#    echo "${directionArray[0]^}"
-#    exit 0
-#    set_monitor 0
-#elif [[ "${rightArray[@]}" =~ $option ]]; then
-#    echo "${directionArray[1]^}"
-#    exit 0
-#    set_monitor 1
-#elif [[ "${downArray[@]}" =~ $option ]]; then
-#    echo "${directionArray[2]^}"
-#    exit 0
-#    set_monitor 2
-#elif [[ "${leftArray[@]}" =~ $option ]]; then
-#    echo "${directionArray[3]^}"
-#    exit 0
-#    set_monitor 3
-#else
-#    echo "Argument $1 is not a valid value."
-#    echo "For help use: $0 -h"
-#    exit 3
-#fi
+# }}}
